run:
  deadline: 5m

linters:
  enable:
    - nlreturn
  disable:
    - exhaustruct
    - goerr113
    - unparam
    - depguard
    - testpackage
    - prealloc
  presets:
    - bugs
    - comment
    - error
    - import
    - performance
    - test
    - unused
